## (C) Copyright IBM Corporation 2016, 2017.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## docker network create --driver overlay --subnet 10.66.0.0/24 prot_celta
## docker network create --driver overlay --subnet 10.18.0.0/24 prot_ceoh
##

version: "3"

services:

    cro-server:
        image: cro812
        environment:
            DISPLAY: $DISPLAY 
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        network: host
        ports:
            - 8080:8080
        container_name: crort
        hostname: crort

    db2node1:
        image: ibmcom/db2
        environment:
            LICENSE: "accept"
            DB2INST1_PASSWORD: "Passw0rd"
            SAMPLEDB: "true"
            HADR_ENABLED: "true"
            HADR_ROLE_FOR_SETUP: "PRIMARY"
            ETCD_ENDPOINT: "IP1:PORT1,IP2:PORT2,IP3:PORT3"
        volumes:
            - /home/rvasquez/database1:/database
            - /home/rvasquez/shared:/hadr
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        network: host
        ipc: host
        privileged: true
        ports:
            - "50001:50000"
            - "55001:55000"
            - "3021:22"
        container_name: db2node1
        hostname: db2node1

    db2node2:
        image: ibmcom/db2
        environment:
            LICENSE: "accept"
            DB2INST1_PASSWORD: "Passw0rd"
            SAMPLEDB: "true"
            HADR_ENABLED: "true"
            HADR_ROLE_FOR_SETUP: "STANDBY"
            ETCD_ENDPOINT: "IP1:PORT1,IP2:PORT2,IP3:PORT3"
        volumes:
            - /home/rvasquez/database2:/database
            - /home/rvasquez/shared:/hadr
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        network: host
        ipc: host
        privileged: true
        ports:
            - "50002:50000"
            - "55002:55000"
            - "3022:22"
        container_name: db2node2
        hostname: db2node2
